/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Apache-2.0
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::path::PathBuf;

// JSON omission policies preserve legacy request and response shapes.
const FABRIC_SERDE_FIELD_ATTRIBUTES: &[(&str, &[&str])] = &[
    (
        r#"#[cfg_attr(feature = "serde", serde(default, skip_serializing_if = "Option::is_none"))]"#,
        &[
            "rack_manager.GetScaleUpFabricStatusRequest.inspection",
            "rack_manager.GetScaleUpFabricStatusResponse.observation",
            "rack_manager.ScaleUpFabricInspection.compute_nodes",
            "rack_manager.ScaleUpFabricInspectionObservation.requested_scope",
            "rack_manager.ScaleUpFabricInspectionObservation.authoritative_primary_node_id",
            "rack_manager.ScaleUpFabricInspectionObservation.topology_type",
            "rack_manager.ScaleUpFabricInspectionObservation.health",
            "rack_manager.ScaleUpFabricInspectionObservation.raw_control_plane_state",
            "rack_manager.ScaleUpFabricInspectionObservation.raw_controller_health",
            "rack_manager.ScaleUpFabricInspectionObservation.matches_requested_nodes",
            "rack_manager.ScaleUpFabricReadResult.node_id",
            "rack_manager.ScaleUpFabricSwitchObservation.location",
            "rack_manager.ScaleUpFabricSwitchObservation.enabled",
            "rack_manager.ScaleUpFabricSwitchObservation.raw_cluster_state",
            "rack_manager.ScaleUpFabricInterfaceObservation.applied_explicit_state",
            "rack_manager.ScaleUpFabricInterfaceObservation.startup_explicit_state",
            "rack_manager.ScaleUpFabricInterfaceObservation.effective_admin_state",
            "rack_manager.ScaleUpFabricInterfaceObservation.raw_operational_state",
            "rack_manager.ScaleUpFabricInterfaceObservation.raw_physical_state",
            "rack_manager.ScaleUpFabricComputeObservation.location",
            "rack_manager.ScaleUpFabricMemberObservation.node_id",
            "rack_manager.ScaleUpFabricMemberObservation.chassis_serial_number",
            "rack_manager.ScaleUpFabricMemberObservation.tray_index",
            "rack_manager.ScaleUpFabricMemberObservation.raw_device_health",
            "rack_manager.ScaleUpFabricMemberObservation.raw_node_health",
            "rack_manager_v2.ConfigureScaleUpFabricManagerRequest.layout",
            "rack_manager_v2.ConfigureScaleUpFabricManagerRequest.compute_nodes",
            "rack_manager.ScaleUpFabricNodeLocation.chassis_serial_number",
            "rack_manager.ScaleUpFabricNodeLocation.tray_index",
            "rack_manager.ScaleUpFabricNodeLocation.slot_number",
            "rack_manager_v2.ScaleUpFabricSpec.primary_switch_node_id",
        ],
    ),
    (
        r#"#[cfg_attr(feature = "serde", serde(default, skip_serializing_if = "Vec::is_empty"))]"#,
        &[
            "rack_manager_v2.ConfigureScaleUpFabricManagerResponse.resolved_fabrics",
            "rack_manager_v2.ScaleUpFabricAssignment.compute_node_ids",
            "rack_manager_v2.ScaleUpFabricAssignment.switch_node_ids",
        ],
    ),
    (
        r#"#[cfg_attr(feature = "serde", serde(default, with = "crate::timestamp_serde", skip_serializing_if = "Option::is_none"))]"#,
        &[
            "rack_manager.ScaleUpFabricObservation.collection_started_at",
            "rack_manager.ScaleUpFabricObservation.collection_finished_at",
        ],
    ),
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let build_client = std::env::var_os("CARGO_FEATURE_CLIENT").is_some();
    let build_server = std::env::var_os("CARGO_FEATURE_SERVER").is_some();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let autogenerated_rust_output_directory = out_dir.clone();
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("rms.bin");

    let mut protobuf = tonic_prost_build::configure();

    for &(attribute, fields) in FABRIC_SERDE_FIELD_ATTRIBUTES {
        for &field in fields {
            protobuf = protobuf.field_attribute(field, attribute);
        }
    }

    protobuf
        .file_descriptor_set_path(reflection)
        // Leading dot makes this a prefix match in prost-build's PathMap, covering every message
        // and enum whose FQN starts with ".rack_manager" (i.e. the entire package).
        .type_attribute(
            ".rack_manager",
            "#[cfg_attr(feature = \"serde\", derive(serde::Deserialize, serde::Serialize))]",
        )
        .type_attribute(
            ".rack_manager_v2",
            "#[cfg_attr(feature = \"serde\", derive(serde::Deserialize, serde::Serialize))]",
        )
        // Preserve the serialized shape for callers that do not use the additive field.
        .field_attribute(
            "rack_manager.NodeInfo.additional_host_endpoints",
            "#[cfg_attr(feature = \"serde\", serde(default, skip_serializing_if = \"Vec::is_empty\"))]",
        )
        // prost_types::Timestamp does not implement serde, so each timestamp field
        // needs the crate adapter while the rest of the package can use type_attribute.
        .field_attribute(
            "rack_manager.FirmwareObject.created",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.FirmwareObject.updated",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.FirmwareObjectHistoryRecord.applied_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetFirmwareJobStatusResponse.created_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetFirmwareJobStatusResponse.updated_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetSwitchSystemImageJobStatusResponse.created_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetSwitchSystemImageJobStatusResponse.updated_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetConfigureSwitchCertificateJobStatusResponse.created_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.GetConfigureSwitchCertificateJobStatusResponse.updated_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.JobStatus.created_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.JobStatus.updated_at",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .field_attribute(
            "rack_manager.SwitchSpdmAttestationTargetResult.collection_timestamp",
            "#[cfg_attr(feature = \"serde\", serde(default, with = \"crate::timestamp_serde\"))]",
        )
        .include_file("prost_common.rs")
        .build_server(build_server)
        .build_client(build_client)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(
            &["proto/rack_manager.proto", "proto/rack_manager_v2.proto"],
            &["proto"],
        )
        .unwrap();

    #[cfg(feature = "client")]
    write_client_wrapper(out_dir)?;

    Ok(())
}

#[cfg(feature = "client")]
fn write_client_wrapper(out_dir: PathBuf) -> Result<(), Box<dyn std::error::Error>> {
    use tonic_client_wrapper::codegen;

    let rms_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "RackManagerApiClient".to_string(),
        inner_rpc_client_type: "crate::RackManagerClientT".to_string(),
        proto_files: vec!["proto/rack_manager.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    rms_client_wrapper.write_rpc_client_wrapper(out_dir.join("rack_manager_client.rs"))?;
    rms_client_wrapper
        .write_rpc_convenience_converters(out_dir.join("rack_manager_converters.rs"))?;

    let rms_v2_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "RackManagerV2ApiClient".to_string(),
        inner_rpc_client_type: "crate::RackManagerV2ClientT".to_string(),
        proto_files: vec!["proto/rack_manager_v2.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        // Keep in sync with rack_manager.* field types imported in proto/rack_manager_v2.proto.
        // Any new cross-package type used in rack_manager_v2.proto must be added here or the
        // generated code will reference a wrong path and fail to compile.
        extern_paths: vec![
            (
                ".rack_manager.NodeSet",
                "crate::protos::rack_manager::NodeSet",
            ),
            (
                ".rack_manager.ScaleUpFabricStaticConfig",
                "crate::protos::rack_manager::ScaleUpFabricStaticConfig",
            ),
        ],
        generated_types_path_within_crate: "protos".to_string(),
    })?;

    rms_v2_client_wrapper.write_rpc_client_wrapper(out_dir.join("rack_manager_v2_client.rs"))?;

    rms_v2_client_wrapper
        .write_rpc_convenience_converters(out_dir.join("rack_manager_v2_converters.rs"))?;

    Ok(())
}
